name: ccompile
version: 0.2.3
author: Andrew Mezoni <andrew.mezoni@gmail.com>
description: Library for compiling C/C++ source files from Dart scripts. The main purpose of compiling native extensions from Dart source files. It is also possible to use this to compile any other small projects.
homepage: https://github.com/mezoni/ccompile
dependencies:
  args: any
  ccompilers: any
  map_parser:
    git: https://github.com/mezoni/map_parser
  path: any
  yaml: any
