name: ccompile
version: 0.1.18+201307031747
author: Andrew Mezoni <andrew.mezoni@gmail.com>
description: Library for compiling C/C++ source files from Dart scripts. The main purpose of compiling native extensions from Dart source files. It is also possible to use this to compile any other small projects.
homepage: https://github.com/mezoni/ccompile
dependencies:
  args: any
  async:
    git: https://github.com/mezoni/async
  mezoni_parser:
    git: https://github.com/mezoni/mezoni_parser
  yaml: any
